In [2]:
import pandas as pd

# Load  dataset
df = pd.read_csv('iperbole-wifi-affollamento.csv',sep=';')

In [3]:
df.drop(inplace=True,columns='id.1')

In [4]:
float(df['geo_point_2d'][0].split(', ')[0])

df['lat']=[float(e.split(', ')[0]) for e in df['geo_point_2d']]
df['long']=[float(e.split(', ')[1]) for e in df['geo_point_2d']]

In [5]:
df.drop(inplace=True,columns='geo_point_2d')

In [6]:
df.drop(inplace=True,columns='shape_copertura')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 264494 entries, 0 to 264493
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   codice_zona         264494 non-null  str
 1   nome_zona           264494 non-null  str
 2   data                264494 non-null  str
 3   giorno              264494 non-null  str
 4   ora                 264494 non-null  int64
 5   affollamento_medio  264494 non-null  int64
 6   lat                 264494 non-null  float64
 7   long                264494 non-null  float64
dtypes: float64(2), int64(2), str(4)
memory usage: 16.1 MB

In [8]:
df.head()

,codice_zona,nome_zona,data,giorno,ora,affollamento_medio,lat,long
0,comune_liber_paradisus,Comune / Piazza Liber Paradisus,2026-01-05T08:00:00+00:00,1-Lunedi,9,110,44.509630,11.340079
1,giardino_vittime_macinella,Giardino Vittime di Marcinelle e Caduti,2026-01-05T08:00:00+00:00,1-Lunedi,9,50,44.505008,11.367729
2,laboratorio_interculturale,Biblioteca del Laboratorio Interculturale,2026-01-05T08:00:00+00:00,1-Lunedi,9,10,44.492325,11.334051
3,mambo,Mambo,2026-01-05T08:00:00+00:00,1-Lunedi,9,30,44.502577,11.336834
4,mercato_san_donato,Mercato San Donato,2026-01-05T08:00:00+00:00,1-Lunedi,9,0,44.502019,11.362215

In [9]:
df.describe()

                 ora  affollamento_medio            lat           long
count  264494.000000       264494.000000  264494.000000  264494.000000
mean       11.499323           40.530409      44.499749      11.345115
std         6.922649           91.693851       0.012087       0.025767
min         0.000000            0.000000      44.473549      11.265671
25%         5.000000            0.000000      44.492867      11.335924
50%        11.000000           10.000000      44.496882      11.344318
75%        17.000000           30.000000      44.504597      11.357190
max        23.000000         1770.000000      44.546273      11.394655

In [10]:
df.corr(numeric_only=True)

                         ora  affollamento_medio       lat      long
ora                 1.000000            0.138791  0.000050  0.000007
affollamento_medio  0.138791            1.000000 -0.062916 -0.019156
lat                 0.000050           -0.062916  1.000000 -0.193572
long                0.000007           -0.019156 -0.193572  1.000000

In [11]:

df['data']=[d.split('T')[0] for d in df['data']]

date_convertite = pd.to_datetime(df['data']).dt.date

print(date_convertite.nunique())

146

In [12]:
date_convertite

0         2026-01-05
1         2026-01-05
2         2026-01-05
3         2026-01-05
4         2026-01-05
             ...
264489    2026-01-14
264490    2026-01-14
264491    2026-01-14
264492    2026-01-14
264493    2026-01-14
Name: data, Length: 264494, dtype: object

In [13]:
map_data_int={}
lista_date=date_convertite.unique().tolist()
lista_date.sort()
print(lista_date)
map_data_int={str(data): i for i,data in enumerate(lista_date)}
print(map_data_int)

[datetime.date(2025, 12, 31), datetime.date(2026, 1, 1), datetime.date(2026, 1, 2), datetime.date(2026, 1, 3), datetime.date(2026, 1, 4), datetime.date(2026, 1, 5), datetime.date(2026, 1, 6), datetime.date(2026, 1, 7), datetime.date(2026, 1, 8), datetime.date(2026, 1, 9), datetime.date(2026, 1, 10), datetime.date(2026, 1, 11), datetime.date(2026, 1, 12), datetime.date(2026, 1, 13), datetime.date(2026, 1, 14), datetime.date(2026, 1, 15), datetime.date(2026, 1, 16), datetime.date(2026, 1, 17), datetime.date(2026, 1, 18), datetime.date(2026, 1, 19), datetime.date(2026, 1, 20), datetime.date(2026, 1, 21), datetime.date(2026, 1, 22), datetime.date(2026, 1, 23), datetime.date(2026, 1, 24), datetime.date(2026, 1, 25), datetime.date(2026, 1, 26), datetime.date(2026, 1, 27), datetime.date(2026, 1, 28), datetime.date(2026, 1, 29), datetime.date(2026, 1, 30), datetime.date(2026, 1, 31), datetime.date(2026, 2, 1), datetime.date(2026, 2, 2), datetime.date(2026, 2, 3), datetime.date(2026, 2, 4), datetime.date(2026, 2, 5), datetime.date(2026, 2, 6), datetime.date(2026, 2, 7), datetime.date(2026, 2, 8), datetime.date(2026, 2, 9), datetime.date(2026, 2, 10), datetime.date(2026, 2, 11), datetime.date(2026, 2, 12), datetime.date(2026, 2, 13), datetime.date(2026, 2, 14), datetime.date(2026, 2, 15), datetime.date(2026, 2, 16), datetime.date(2026, 2, 17), datetime.date(2026, 2, 18), datetime.date(2026, 2, 19), datetime.date(2026, 2, 20), datetime.date(2026, 2, 21), datetime.date(2026, 2, 22), datetime.date(2026, 2, 23), datetime.date(2026, 2, 24), datetime.date(2026, 2, 25), datetime.date(2026, 2, 26), datetime.date(2026, 2, 27), datetime.date(2026, 2, 28), datetime.date(2026, 3, 1), datetime.date(2026, 3, 2), datetime.date(2026, 3, 3), datetime.date(2026, 3, 4), datetime.date(2026, 3, 5), datetime.date(2026, 3, 6), datetime.date(2026, 3, 7), datetime.date(2026, 3, 8), datetime.date(2026, 3, 9), datetime.date(2026, 3, 10), datetime.date(2026, 3, 11), datetime.date(2026, 3, 12), datetime.date(2026, 3, 13), datetime.date(2026, 3, 14), datetime.date(2026, 3, 15), datetime.date(2026, 3, 16), datetime.date(2026, 3, 17), datetime.date(2026, 3, 18), datetime.date(2026, 3, 19), datetime.date(2026, 3, 20), datetime.date(2026, 3, 21), datetime.date(2026, 3, 22), datetime.date(2026, 3, 23), datetime.date(2026, 3, 24), datetime.date(2026, 3, 25), datetime.date(2026, 3, 26), datetime.date(2026, 3, 27), datetime.date(2026, 3, 28), datetime.date(2026, 3, 29), datetime.date(2026, 3, 30), datetime.date(2026, 3, 31), datetime.date(2026, 4, 1), datetime.date(2026, 4, 2), datetime.date(2026, 4, 3), datetime.date(2026, 4, 4), datetime.date(2026, 4, 5), datetime.date(2026, 4, 6), datetime.date(2026, 4, 7), datetime.date(2026, 4, 8), datetime.date(2026, 4, 9), datetime.date(2026, 4, 10), datetime.date(2026, 4, 11), datetime.date(2026, 4, 12), datetime.date(2026, 4, 13), datetime.date(2026, 4, 14), datetime.date(2026, 4, 15), datetime.date(2026, 4, 16), datetime.date(2026, 4, 17), datetime.date(2026, 4, 18), datetime.date(2026, 4, 19), datetime.date(2026, 4, 20), datetime.date(2026, 4, 21), datetime.date(2026, 4, 22), datetime.date(2026, 4, 23), datetime.date(2026, 4, 24), datetime.date(2026, 4, 25), datetime.date(2026, 4, 26), datetime.date(2026, 4, 27), datetime.date(2026, 4, 28), datetime.date(2026, 4, 29), datetime.date(2026, 4, 30), datetime.date(2026, 5, 1), datetime.date(2026, 5, 2), datetime.date(2026, 5, 3), datetime.date(2026, 5, 4), datetime.date(2026, 5, 5), datetime.date(2026, 5, 6), datetime.date(2026, 5, 7), datetime.date(2026, 5, 8), datetime.date(2026, 5, 9), datetime.date(2026, 5, 10), datetime.date(2026, 5, 11), datetime.date(2026, 5, 12), datetime.date(2026, 5, 13), datetime.date(2026, 5, 14), datetime.date(2026, 5, 15), datetime.date(2026, 5, 16), datetime.date(2026, 5, 17), datetime.date(2026, 5, 18), datetime.date(2026, 5, 19), datetime.date(2026, 5, 20), datetime.date(2026, 5, 21), datetime.date(2026, 5, 22), datetime.date(2026, 5, 23), datetime.date(2026, 5, 24), datetime.date(2026, 5, 25)]
{'2025-12-31': 0, '2026-01-01': 1, '2026-01-02': 2, '2026-01-03': 3, '2026-01-04': 4, '2026-01-05': 5, '2026-01-06': 6, '2026-01-07': 7, '2026-01-08': 8, '2026-01-09': 9, '2026-01-10': 10, '2026-01-11': 11, '2026-01-12': 12, '2026-01-13': 13, '2026-01-14': 14, '2026-01-15': 15, '2026-01-16': 16, '2026-01-17': 17, '2026-01-18': 18, '2026-01-19': 19, '2026-01-20': 20, '2026-01-21': 21, '2026-01-22': 22, '2026-01-23': 23, '2026-01-24': 24, '2026-01-25': 25, '2026-01-26': 26, '2026-01-27': 27, '2026-01-28': 28, '2026-01-29': 29, '2026-01-30': 30, '2026-01-31': 31, '2026-02-01': 32, '2026-02-02': 33, '2026-02-03': 34, '2026-02-04': 35, '2026-02-05': 36, '2026-02-06': 37, '2026-02-07': 38, '2026-02-08': 39, '2026-02-09': 40, '2026-02-10': 41, '2026-02-11': 42, '2026-02-12': 43, '2026-02-13': 44, '2026-02-14': 45, '2026-02-15': 46, '2026-02-16': 47, '2026-02-17': 48, '2026-02-18': 49, '2026-02-19': 50, '2026-02-20': 51, '2026-02-21': 52, '2026-02-22': 53, '2026-02-23': 54, '2026-02-24': 55, '2026-02-25': 56, '2026-02-26': 57, '2026-02-27': 58, '2026-02-28': 59, '2026-03-01': 60, '2026-03-02': 61, '2026-03-03': 62, '2026-03-04': 63, '2026-03-05': 64, '2026-03-06': 65, '2026-03-07': 66, '2026-03-08': 67, '2026-03-09': 68, '2026-03-10': 69, '2026-03-11': 70, '2026-03-12': 71, '2026-03-13': 72, '2026-03-14': 73, '2026-03-15': 74, '2026-03-16': 75, '2026-03-17': 76, '2026-03-18': 77, '2026-03-19': 78, '2026-03-20': 79, '2026-03-21': 80, '2026-03-22': 81, '2026-03-23': 82, '2026-03-24': 83, '2026-03-25': 84, '2026-03-26': 85, '2026-03-27': 86, '2026-03-28': 87, '2026-03-29': 88, '2026-03-30': 89, '2026-03-31': 90, '2026-04-01': 91, '2026-04-02': 92, '2026-04-03': 93, '2026-04-04': 94, '2026-04-05': 95, '2026-04-06': 96, '2026-04-07': 97, '2026-04-08': 98, '2026-04-09': 99, '2026-04-10': 100, '2026-04-11': 101, '2026-04-12': 102, '2026-04-13': 103, '2026-04-14': 104, '2026-04-15': 105, '2026-04-16': 106, '2026-04-17': 107, '2026-04-18': 108, '2026-04-19': 109, '2026-04-20': 110, '2026-04-21': 111, '2026-04-22': 112, '2026-04-23': 113, '2026-04-24': 114, '2026-04-25': 115, '2026-04-26': 116, '2026-04-27': 117, '2026-04-28': 118, '2026-04-29': 119, '2026-04-30': 120, '2026-05-01': 121, '2026-05-02': 122, '2026-05-03': 123, '2026-05-04': 124, '2026-05-05': 125, '2026-05-06': 126, '2026-05-07': 127, '2026-05-08': 128, '2026-05-09': 129, '2026-05-10': 130, '2026-05-11': 131, '2026-05-12': 132, '2026-05-13': 133, '2026-05-14': 134, '2026-05-15': 135, '2026-05-16': 136, '2026-05-17': 137, '2026-05-18': 138, '2026-05-19': 139, '2026-05-20': 140, '2026-05-21': 141, '2026-05-22': 142, '2026-05-23': 143, '2026-05-24': 144, '2026-05-25': 145}

In [17]:
print(str(date_convertite[0]))
date_convertite=[map_data_int[str(e)] for e in date_convertite]
print(date_convertite)

2026-01-05

In [18]:
df['data']=date_convertite

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 264494 entries, 0 to 264493
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   codice_zona         264494 non-null  str
 1   nome_zona           264494 non-null  str
 2   data                264494 non-null  int64
 3   giorno              264494 non-null  str
 4   ora                 264494 non-null  int64
 5   affollamento_medio  264494 non-null  int64
 6   lat                 264494 non-null  float64
 7   long                264494 non-null  float64
dtypes: float64(2), int64(3), str(3)
memory usage: 16.1 MB